# Generated by Django 4.2.4 on 2023-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionarries',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='questionarries',
            name='petname',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='questionarries',
            name='pettype',
            field=models.TextField(default=0),
        ),
    ]
