# Generated by Django 4.2.4 on 2023-09-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_questionarries_pet_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionarries',
            new_name='Questionarie',
        ),
    ]
