# Generated by Django 4.2.4 on 2023-09-26 04:08

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createPETLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('auction_status', models.BooleanField(default=io.open)),
                ('allocated_manager', models.CharField(max_length=15)),
            ],
        ),
    ]
