# Generated by Django 4.2.4 on 2023-09-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpetlist',
            name='allocated_manager',
        ),
        migrations.RemoveField(
            model_name='createpetlist',
            name='auction_status',
        ),
    ]
