# Generated by Django 4.2.4 on 2023-09-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_createpetlist_allocated_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(default=0)),
                ('contact', models.IntegerField(default=0)),
                ('services', models.TextField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='createPETLIST',
        ),
    ]
